setw -g mouse on

# Change the key for horizontal split
bind h split-window -h

# Change the key for vertical split
bind v split-window -v

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Ensure window index numbers get reordered on delete.
set-option -g renumber-windows on
