import = ["~/.config/alacritty/themes/default.toml"]
#import = ["~/.config/alacritty/themes/cyberdream-light.toml"]
#import = ["~/.config/alacritty/themes/cyberdream.toml"]

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window.padding]
x = 5
y = 5

[window]
option_as_alt = "OnlyLeft"

